# Generated by Django 4.2.7 on 2024-11-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=15)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spksaw.bidang')),
            ],
        ),
    ]
