# Generated by Django 4.2.7 on 2024-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0002_pegawai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pegawai',
            old_name='nama_pegawai',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='nomor_induk',
            field=models.CharField(default='N/A', max_length=20, unique=True),
        ),
    ]
