# Generated by Django 4.2.7 on 2024-11-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0003_rename_nama_pegawai_pegawai_nama_pegawai_nomor_induk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='nomor_induk',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
