# Generated by Django 4.2.7 on 2024-11-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0004_alter_pegawai_nomor_induk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidang',
            options={'ordering': ['id'], 'verbose_name_plural': 'Bidang'},
        ),
        migrations.AlterModelOptions(
            name='pegawai',
            options={'ordering': ['nama'], 'verbose_name_plural': 'Pegawai'},
        ),
    ]
