# Generated by Django 4.2.7 on 2024-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0005_alter_bidang_options_alter_pegawai_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='nomor_induk',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
