# Generated by Django 4.2.7 on 2024-11-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0006_alter_pegawai_nomor_induk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField(default=0)),
                ('tipe_kriteria', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], default='benefit', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Kriteria',
                'ordering': ['nama'],
            },
        ),
    ]
