# Generated by Django 4.2.7 on 2024-11-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0007_kriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.TextField(blank=True, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spksaw.bidang')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spksaw.pegawai')),
            ],
            options={
                'verbose_name_plural': 'Penilaian',
                'ordering': ['nama'],
            },
        ),
    ]
