# Generated by Django 4.2.7 on 2024-12-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0008_penilaian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kriteria',
            old_name='tipe_kriteria',
            new_name='tipe',
        ),
    ]
