# Generated by Django 4.2.7 on 2024-12-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0009_rename_tipe_kriteria_kriteria_tipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PegawaiTerbaik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('bidang', models.CharField(max_length=100)),
                ('normalisasi_nilai', models.TextField()),
                ('nilai_preferensi', models.FloatField()),
                ('tahun_penilaian', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pegawai Terbaik',
                'ordering': ['-tahun_penilaian', '-nilai_preferensi'],
            },
        ),
    ]
