# Generated by Django 4.2.7 on 2024-12-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spksaw', '0010_pegawaiterbaik'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPenilaian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.TextField()),
                ('tahun_penilaian', models.IntegerField()),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penilaian', to='spksaw.bidang')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penilaian', to='spksaw.pegawai')),
            ],
            options={
                'verbose_name_plural': 'Riwayat Penilaian',
                'ordering': ['id'],
            },
        ),
    ]
